# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details

---
fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
    vcsrepo:
      repo: https://github.com/puppetlabs/puppetlabs-vcsrepo.git
    rhsm:
      repo: https://github.com/voxpupuli/puppet-rhsm.git
    epel:
      repo: https://github.com/voxpupuli/puppet-epel.git
    systemd:
      repo: https://github.com/camptocamp/puppet-systemd.git
  symlinks:
    oxidized: "#{source_dir}"
