# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details

---
fixtures:
  forge_modules:
    stdlib:
      repo: puppetlabs/stdlib
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
    rhsm:
      repo: puppet/rhsm
    epel:
      repo: puppet/epel
    systemd:
      repo: puppet/systemd
    alternatives:
      repo: puppet/alternatives
  symlinks:
    oxidized: "#{source_dir}"
