---
.github/workflows/ci.yaml:
  acceptance_matrix:
    set:
      - el7
      - el8
      - ---el9
      - debian-9
      - debian-10
      - ubuntu-1804
      - ubuntu-2004
    puppet:
      - puppet6
      - puppet7
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/el8.yml:
  update: true
spec/acceptance/nodesets/el9.yml:
  delete: true
spec/acceptance/nodesets/debian-11.yml:
  delete: true
